#!/bin/sh
set -e

# make dir for config
mkdir -p /config \
	 /tmp/xteve \
;
  chown xteve:xteve /config \
	 /tmp/xteve \
;

# permissions
chmod -R 777 /config

XTEVE_FILE=/config/xteve.conf

if [ -f "$XTEVE_FILE" ]; then
	set -- "$(sed -n '1p' $XTEVE_FILE)" "$@"
else
	echo "xteve -port=34400 -config=/root/.xteve/test/
### remove from here including this line ###
### edit your xteve command
### rename to xteve.txt
### restart docker, xteve will run with given parameter
### no xteve.txt it ll start default values -port=34400 -config=/root/.xteve/" > /config/sample_xteve.conf
	echo "xteve -port=80 -config=/config/" > $XTEVE_FILE
	set -- xteve -port=80 -config=/config/ "$@"
fi

# allow the container to be started with `--user`
if [ "$1" = 'xteve' -a "$(id -u)" = '0' ]; then
    exec su-exec xteve "$0" "$@"
fi

exec "$@"
