#!/bin/sh
set -e

# set default permission id
DEFAULT_PUID=1000
DEFAULT_PGID=1000

# Read from env，use default if not set
PUID=${PUID:-$DEFAULT_PUID}
PGID=${PGID:-$DEFAULT_PGID}

echo "Starting with PUID=$PUID, PGID=$PGID"

# Change user group id：if group with PGID not exit，change xteve group gid to PGID；else，change xteve user to PGID group
if [ ! getent group "$PGID" >/dev/null ] ; then
    echo "Changing xteve group GID from $(getent group xteve | cut -d: -f3) to $PGID"
    groupmod -g "$PGID" xteve
else
    existing_group=$(getent group "$PGID" | cut -d: -f1)
    usermod -g "$existing_group" xteve
fi

# Change xteve user's UID
if [ "$(id -u xteve)" != "$PUID" ]; then
    echo "Changing xteve user UID from $(id -u xteve) to $PUID"
    usermod -u "$PUID" -g "$PGID" xteve
fi

# make dir for config
mkdir -p /config \
  /tmp/xteve

chown -R "$PUID:$PGID" \
  /config \
  /tmp/xteve

# permissions
chmod -R 755 /config

XTEVE_FILE=/config/xteve.conf

if  [ ! "$1" ]; then
  if [ -f "$XTEVE_FILE" ]; then
    set -- "$(sed -n '1p' $XTEVE_FILE)" "$@"
    set -- "$(sed -n '2p' $XTEVE_FILE)" "$@"
  else
    su-exec xteve echo "-port=34400
-config=/root/.xteve/test/
### remove from here including this line ###
### edit your xteve command
### rename to xteve.txt
### restart docker, xteve will run with given parameter
### no xteve.txt it ll start default values -port=34400 -config=/root/.xteve/" > /config/sample_xteve.conf
    su-exec xteve echo "-port=80
-config=/config/" > $XTEVE_FILE
    set -- -port=80 "$@"
    set -- -config=/config/ "$@"
  fi
fi

# first arg is `--some-option`
if [ "${1#-}" != "$1" ]; then
  set -- xteve "$@"
fi

# allow the container to be started with `--user`
if [ "$1" = 'xteve' -a "$(id -u)" = '0' ]; then
  exec su-exec xteve "$0" "$@"
fi

exec "$@"
